//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.239
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambitour.GUI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GraphicSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GraphicSettings defaultInstance = ((GraphicSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GraphicSettings())));
        
        public static GraphicSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ivory")]
        public global::System.Drawing.Color BgColor {
            get {
                return ((global::System.Drawing.Color)(this["BgColor"]));
            }
            set {
                this["BgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FixedToolWindow")]
        public global::System.Windows.Forms.FormBorderStyle FormBorderStyle {
            get {
                return ((global::System.Windows.Forms.FormBorderStyle)(this["FormBorderStyle"]));
            }
            set {
                this["FormBorderStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("790, 617")]
        public global::System.Drawing.Size LeftPanelSize {
            get {
                return ((global::System.Drawing.Size)(this["LeftPanelSize"]));
            }
            set {
                this["LeftPanelSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("223, 617")]
        public global::System.Drawing.Size RightPanelSize {
            get {
                return ((global::System.Drawing.Size)(this["RightPanelSize"]));
            }
            set {
                this["RightPanelSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("790, 90")]
        public global::System.Drawing.Point RightPanelPoint {
            get {
                return ((global::System.Drawing.Point)(this["RightPanelPoint"]));
            }
            set {
                this["RightPanelPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 90")]
        public global::System.Drawing.Point LeftPanelPoint {
            get {
                return ((global::System.Drawing.Point)(this["LeftPanelPoint"]));
            }
            set {
                this["LeftPanelPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1013, 90")]
        public global::System.Drawing.Size TopPanelSize {
            get {
                return ((global::System.Drawing.Size)(this["TopPanelSize"]));
            }
            set {
                this["TopPanelSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 49")]
        public global::System.Drawing.Point TopPanelPoint {
            get {
                return ((global::System.Drawing.Point)(this["TopPanelPoint"]));
            }
            set {
                this["TopPanelPoint"] = value;
            }
        }
    }
}
