//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambitour.CoucheMetier {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class GlobalSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalSettings defaultInstance = ((GlobalSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalSettings())));
        
        public static GlobalSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\dossiers")]
        public string strRepertoireLocalDossiersDeFabrication {
            get {
                return ((string)(this["strRepertoireLocalDossiersDeFabrication"]));
            }
            set {
                this["strRepertoireLocalDossiersDeFabrication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\etuls.stockage.univ-lorraine.fr\\etu_commun\\aipl\\Partages\\Ambitour")]
        public string strQueuePath {
            get {
                return ((string)(this["strQueuePath"]));
            }
            set {
                this["strQueuePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Archives")]
        public string strDefaultArchiveQueueName {
            get {
                return ((string)(this["strDefaultArchiveQueueName"]));
            }
            set {
                this["strDefaultArchiveQueueName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\demos")]
        public string strRepertoireDossiersDemo {
            get {
                return ((string)(this["strRepertoireDossiersDemo"]));
            }
            set {
                this["strRepertoireDossiersDemo"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PresenceCN {
            get {
                return ((bool)(this["PresenceCN"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".xpi")]
        public string ExtensionProgrammePiece {
            get {
                return ((string)(this["ExtensionProgrammePiece"]));
            }
            set {
                this["ExtensionProgrammePiece"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".html")]
        public string ExtensionAideHtml {
            get {
                return ((string)(this["ExtensionAideHtml"]));
            }
            set {
                this["ExtensionAideHtml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LDAP://DC=ad,DC=univ-lorraine,DC=fr")]
        public string strADPath {
            get {
                return ((string)(this["strADPath"]));
            }
            set {
                this["strADPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aip-adread")]
        public string strLogin {
            get {
                return ((string)(this["strLogin"]));
            }
            set {
                this["strLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gzero01!")]
        public string strPasswd {
            get {
                return ((string)(this["strPasswd"]));
            }
            set {
                this["strPasswd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\incomingRequest")]
        public string incomingRequestDirectory {
            get {
                return ((string)(this["incomingRequestDirectory"]));
            }
            set {
                this["incomingRequestDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\outgoingRequest")]
        public string outgoingRequestDirectory {
            get {
                return ((string)(this["outgoingRequestDirectory"]));
            }
            set {
                this["outgoingRequestDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\tempRequest")]
        public string tempRequestDirectory {
            get {
                return ((string)(this["tempRequestDirectory"]));
            }
            set {
                this["tempRequestDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\incomingOF")]
        public string incomingOFDirectory {
            get {
                return ((string)(this["incomingOFDirectory"]));
            }
            set {
                this["incomingOFDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\incomingOF\\archives")]
        public string archivesOFDirectory {
            get {
                return ((string)(this["archivesOFDirectory"]));
            }
            set {
                this["archivesOFDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\incomingOF\\temp")]
        public string tempOFDirectory {
            get {
                return ((string)(this["tempOFDirectory"]));
            }
            set {
                this["tempOFDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\outgoingOF")]
        public string outgoingOFDirectory {
            get {
                return ((string)(this["outgoingOFDirectory"]));
            }
            set {
                this["outgoingOFDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.68.92")]
        public string jadeServerAddress {
            get {
                return ((string)(this["jadeServerAddress"]));
            }
            set {
                this["jadeServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ambitour\\DossiersAmbiflux")]
        public string repertoireDossiersAmbiflux {
            get {
                return ((string)(this["repertoireDossiersAmbiflux"]));
            }
            set {
                this["repertoireDossiersAmbiflux"] = value;
            }
        }
    }
}
